name: Bug report
description: Fill in this form to report a bug.

body:
  - type: dropdown
    id: platform
    attributes:
      label: Platforms
      description: On what platform have you found this bug?
      multiple: false
      options:
        - Android
        - Mac
        - Windows
        - Linux
    validations:
      required: true
  - type: input
    id: game-build
    attributes:
      label: Game Build
      description: The game's build number under the title in the main menu.
      placeholder: LATEST IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER.
    validations:
      required: true
  - type: input
    id: mod-build
    attributes:
      label: Mod Build / Version
      description: The mod's version which appears under its description.
      placeholder: LATEST IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER.
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Explain your issue in detail.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How you happened across the issue, and what exactly you did to make the bug happen.
    validations:
      required: true
  - type: textarea
    id: mods
    attributes:
      label: Mods used
      description: A list of ALL the mods you have enabled at the time, including FOS and FOS OST.
    validations:
      required: true
  - type: textarea
    id: save-file
    attributes:
      label: Save file
      description: The (zipped) save file you were playing on when the bug happened. If this happened in the campaign, specify the sector, and attach the file you get from Settings -> Game Data -> Export Data. For custom games, attach the .msav file exported from the save dialog, zipped.
      placeholder: THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: (Crash) logs
      description: Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs.
      placeholder: REQUIRED if you are reporting a crash.
    validations:
      required: false
  - type: checkboxes
    id: agreement
    attributes:
      label: Submission
      description: Check the boxes to confirm that you have read the lines below.
      options:
        - label: I have updated to the latest release (https://github.com/TeamOct/FOS/releases) to make sure my issue has not been fixed.
          required: true
        - label: I have searched the closed and open issues to make sure that this problem has not already been reported.
          required: true
        - label: I am sure that the bug is not caused by other mods I have installed, or, in rare cases, the game itself.
          required: true